[package]
name = "chapter9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getch-rs = "0.1"
rand = "0.8.5"
clap = { version = "4.1.4", features = ["derive"] }
